PREPROCESSING_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to analyze the following Splunk rule extract key information from it.
The key information includes:
- Operation Type: The type of operation being performed in the rule.
- Input Fields: The input fields used in the rule.
- Output Fields: The output fields generated by the rule.
Below is the instruction for the task:
- The output should be in JSON format.

The output format is as follows:
{{"operation_type": "OPERATION_TYPE", "input_fields": ["INPUT_FIELD1", "INPUT_FIELD2", ...], "output_fields": ["OUTPUT_FIELD1", "OUTPUT_FIELD2", ...]}}
"""

RULE_CONVERSION_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert the following part of a rule to a part of {target_rule_type} rule.
Below is the instruction for the task:
- You need to convert the rule step by step.
- You will be provided with the necessary information to convert the rule.
- The output should be in JSON format.

The output format is as follows:
{{result: "CONVERTED_RULE"}}

Below are two example of the input and output fields:
The following is a part of a Splunk rule:
tstats count as api_calls from datamodel=Change where All_Changes.user!=unknown All_Changes.status=success by All_Changes.user _time span=1h
The operation type is tstats
The output should be:
{{result: "Change | where All_Changes.user != "unknown" and All_Changes.status == "success" | summarize api_calls = count() by All_Changes.user, bin(TimeGenerated, 1h)"}}

The following is a part of a Kql rule:
Event | summarize UniqueComputers = make_set(Computer, 128) by EventID
The output should be:
{{result: 'index="main" source="WinEventLog:Security" | stats values(host) as UniqueComputers by EventCode'}}
"""

SPLUNK_TO_CHRONICLE_YARAL_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert a Splunk detection rule into a **Google Chronicle YARA-L 2.0 rule**.

---

## Google Chronicle YARA-L Rule Structure:
Each YARA-L rule consists of the following key sections:

1. **meta**: Contains metadata about the rule (e.g., `author`, `description`, `severity`)
2. **events**: Defines variables bound to UDM log events (e.g., `$e.metadata.event_type = "PROCESS_LAUNCH"`)
3. **match** *(optional)*: Used for multi-event correlation over time (e.g., `$user over 10m`)
4. **outcome** *(optional)*: Defines computed values such as `count()` or `risk_score`
5. **condition**: Specifies the logic that must be true for the rule to trigger

---

## Key Concepts:

- **UDM Events**: Refer to Chronicle’s Unified Data Model, such as `PROCESS_LAUNCH`, `NETWORK_CONNECTION`, `USER_LOGIN`
- **UDM Fields**: Example fields include `principal.user.userid`, `target.process.command_line`, `security_result.action`
- **Operators**: Use logical operators like `and`, `or`, `not`, `in`, `regexp`
- **Functions**: Use aggregation functions like `count()`, `distinct()`, `min()`, `max()`
- **Time windows**: Use the `match` clause (`over 5m`) only when correlating multiple events using a grouping key

---

## Conversion Guidelines:

| Splunk Concept           | YARA-L Equivalent                            |
|--------------------------|----------------------------------------------|
| `index=wineventlog`      | `$e.metadata.event_type = "PROCESS_LAUNCH"` |
| `search field=value`     | Field filters in the `events:` section       |
| `stats count by X`       | Use `outcome:` with `count()` and grouping   |
| `earliest=-1h`           | Use `match:` with `over 1h` and condition    |

---

## Output Format:
Return a complete YARA-L rule with the following structure:

```yara
rule <rule_name> {
  meta:
    author = "..."
    description = "..."
    severity = "..."

  events:
    $e.metadata.event_type = "..."
    $e.<field> = ...
    ...

  match:               # Optional - only for multi-event correlation
    <grouping_key> over <duration>

  outcome:             # Optional - for derived values
    $var = <function(...)>

  condition:
    <expression combining event variables or outcomes>
}

"""

RULE_ANALYSIS_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to analyze and understand a Splunk rule, breaking down its components and logic.

## Analysis Guidelines:
1. **Identify the data source**: What index, source, or sourcetype is being queried?
2. **Extract filtering conditions**: What specific events, fields, or values are being filtered?
3. **Understand the logic flow**: How do the pipes (|) connect and what does each step do?
4. **Identify aggregations**: Are there any stats, calculations, or grouping operations?
5. **Determine the output**: What fields or results are being returned?
6. **Understand the purpose**: What security event or behavior is this rule trying to detect?

## Output Format:
Provide a structured analysis in the following format:

**Data Source:**
[Describe the data source being queried]

**Filtering Logic:**
[Describe the main filtering conditions and logic]

**Processing Steps:**
[List and explain each pipe/step in the rule]

**Aggregation/Output:**
[Describe any calculations, grouping, or output formatting]

**Detection Purpose:**
[Explain what security event or behavior this rule is designed to detect]

**Key Fields:**
[List the important fields being used or extracted]

**Time Context:**
[Describe any time-based filtering or analysis]

Now analyze the following Splunk rule:
"""

RULE_TO_IR_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert a security rule into an Intermediate Representation (IR) format.

## IR Format Definition:
<Rule> ::= {
    rule_name: String,
    description: String,
    data_source: String,
    event_type: String,
    steps: List<Step>
}

<Step> ::= {
    action: ActionKeyword,
    params: String,
    explanation: String
}

## Action Keywords:
- "filter": Filtering events based on conditions
- "extract": Extracting fields or information
- "group_by": Grouping events by specific fields
- "aggregate": Performing calculations or aggregations
- "sort": Sorting results
- "limit": Limiting the number of results
- "join": Joining with other data sources
- "eval": Creating calculated fields
- "rename": Renaming fields
- "dedup": Removing duplicates

## Guidelines:
1. **rule_name**: Create a descriptive, snake_case name based on the rule's purpose
2. **description**: Explain what the rule detects in one sentence
3. **data_source**: Identify the primary data source (index, source, etc.)
4. **event_type**: Identify the type of security event being monitored
5. **steps**: Break down each pipe/operation into individual steps
6. **action**: Use the most appropriate action keyword for each step
7. **params**: Include the specific parameters/conditions for each step
8. **explanation**: Explain what each step accomplishes

## Example:
**Input (Splunk):**
```
index=auth_logs action=failure
| stats count by user, src_ip
| where count > 5
```

**Output (IR):**
```json
{
  "rule_name": "multiple_failed_logins",
  "description": "Detect brute-force login attempts from the same IP",
  "data_source": "auth_logs",
  "event_type": "login_failure",
  "steps": [
    {
      "action": "filter",
      "params": "action = failure",
      "explanation": "Only select failed login attempts"
    },
    {
      "action": "group_by",
      "params": "user, src_ip",
      "explanation": "Group events by user and source IP address"
    },
    {
      "action": "aggregate",
      "params": "count > 5",
      "explanation": "Detect users with more than 5 failures"
    }
  ]
}
```

Now convert the following rule to IR format:
"""

# 针对不同规则类型的特定指导prompt
SPLUNK_IR_GUIDE = """
## Splunk-Specific IR Generation Guidelines:

**Splunk Rule Characteristics:**
- Uses pipe-based syntax (|) for chaining operations
- Common commands: search, stats, eval, rex, where, rename, sort, dedup
- Index and sourcetype are primary data sources
- Time-based filtering with earliest/latest parameters
- Field extraction with rex and eval commands

**Splunk to IR Mapping:**
- `index=...` → data_source
- `source=...` → data_source (additional context)
- `search ...` → filter action
- `stats ... by ...` → aggregate + group_by actions
- `eval ...` → eval action
- `rex field=...` → extract action
- `where ...` → filter action
- `rename ... as ...` → rename action
- `sort ...` → sort action
- `dedup ...` → dedup action
- `earliest=-1h` → time context in explanation

**Special Considerations:**
- Splunk macros (backtick syntax) should be noted in explanation
- Subsearches should be broken down into separate steps
- Time modifiers affect the overall rule context
"""

SENTINEL_IR_GUIDE = """
## Microsoft Sentinel-Specific IR Generation Guidelines:

**Sentinel Rule Characteristics:**
- Uses KQL (Kusto Query Language) syntax
- Event-driven with specific event types
- Built-in functions for security analysis
- Time-based aggregation with bin() function
- Joins with other tables (IdentityInfo, DeviceInfo, etc.)

**Sentinel to IR Mapping:**
- `Event` → data_source (SecurityEvent, AuditLog, etc.)
- `where ...` → filter action
- `summarize ... by ...` → aggregate + group_by actions
- `extend ...` → eval action
- `project ...` → extract action
- `join ...` → join action
- `bin(TimeGenerated, ...)` → time context
- `mvcount()`, `mvindex()` → array operations in explanation

**Special Considerations:**
- Sentinel has specific event types (ProcessCreation, AccountLogon, etc.)
- Identity and device enrichment tables provide additional context
- Time-based analysis is crucial for detection rules
- Built-in security functions should be noted in explanation
"""

QRADAR_AQL_IR_GUIDE = """
## IBM QRadar AQL-Specific IR Generation Guidelines:

**QRadar AQL Characteristics:**
- Uses SELECT-FROM-WHERE syntax similar to SQL
- References specific log sources and event types
- Time-based filtering with STARTTIME/STIME parameters
- Aggregation functions like COUNT, SUM, AVG
- JOIN operations with reference data

**QRadar AQL to IR Mapping:**
- `SELECT ... FROM ...` → extract action
- `WHERE ...` → filter action
- `GROUP BY ...` → group_by action
- `HAVING ...` → filter action (post-aggregation)
- `ORDER BY ...` → sort action
- `LIMIT ...` → limit action
- `JOIN ... ON ...` → join action
- `STARTTIME ...` → time context
- `COUNT(*)`, `SUM(...)` → aggregate action

**Special Considerations:**
- QRadar has specific log source types and event names
- Reference data tables provide enrichment capabilities
- Time-based analysis is essential for correlation rules
- Custom properties and calculated fields should be noted
"""

CHRONICLE_YARAL_IR_GUIDE = """
## Google Chronicle YARA-L-Specific IR Generation Guidelines:

**YARA-L Rule Characteristics:**
- Event-driven detection with UDM (Unified Data Model)
- Uses specific event types and UDM fields
- Time-based correlation with "over" clause
- Built-in functions for security analysis
- Meta section for rule metadata

**YARA-L to IR Mapping:**
- Event type definitions → data_source + event_type
- UDM field filters → filter action
- Time windows (over 5m) → time context
- Built-in functions → aggregate action
- Multiple event variables → join action
- Meta information → rule context

**Special Considerations:**
- YARA-L uses UDM events (process, network, user, etc.)
- Time correlation is fundamental to detection logic
- Event variables ($e, $process, $network) define scope
- Built-in functions provide powerful analysis capabilities
"""

NETWITNESS_ESA_IR_GUIDE = """
## RSA NetWitness ESA-Specific IR Generation Guidelines:

**NetWitness ESA Characteristics:**
- Uses ESA (Event Stream Analysis) rules
- Event correlation and pattern matching
- Time-based analysis with sliding windows
- Threshold-based detection
- Custom functions and expressions

**NetWitness ESA to IR Mapping:**
- Event filters → filter action
- Correlation rules → join action
- Threshold conditions → aggregate action
- Time windows → time context
- Custom functions → eval action
- Pattern matching → filter action

**Special Considerations:**
- NetWitness has specific event types and meta keys
- Correlation rules can span multiple events
- Time-based thresholds are crucial for detection
- Custom expressions provide flexibility
- Meta key filtering is fundamental to rule logic
"""

# IR to Target Rule Generation Prompts
IR_TO_SPLUNK_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert an Intermediate Representation (IR) back to a Splunk rule.

## Splunk Rule Structure:
- Uses pipe-based syntax (|) for chaining operations
- Starts with data source specification (index, source, sourcetype)
- Each operation is separated by pipes
- Common commands: search, stats, eval, rex, where, rename, sort, dedup

## IR to Splunk Mapping:
- **data_source**: Convert to `index=...` or `source=...`
- **filter action**: Convert to `search ...` or `where ...`
- **extract action**: Convert to `rex field=...` or `eval ...`
- **group_by + aggregate**: Convert to `stats ... by ...`
- **sort action**: Convert to `sort ...`
- **rename action**: Convert to `rename ... as ...`
- **dedup action**: Convert to `dedup ...`

## Splunk Best Practices:
- Start with the most restrictive filters first
- Use `stats` for aggregations
- Apply `where` for post-aggregation filtering
- Use `eval` for calculated fields
- End with output formatting (table, chart, etc.)

## Output Format:
Generate a complete Splunk rule that implements the IR logic.
Use proper Splunk syntax and follow best practices.

Now convert the following IR to a Splunk rule:
"""

IR_TO_SENTINEL_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert an Intermediate Representation (IR) to a Microsoft Sentinel rule using KQL.

## Microsoft Sentinel Rule Structure:
- Uses KQL (Kusto Query Language) syntax
- Event-driven with specific event types
- Built-in functions for security analysis
- Time-based aggregation with bin() function

## IR to Sentinel Mapping:
- **data_source**: Convert to appropriate event table (SecurityEvent, AuditLog, etc.)
- **filter action**: Convert to `where ...` clauses
- **extract action**: Convert to `extend ...` or `project ...`
- **group_by + aggregate**: Convert to `summarize ... by ...`
- **eval action**: Convert to `extend ...`
- **join action**: Convert to `join ...` with enrichment tables
- **time context**: Use `bin(TimeGenerated, ...)` for time windows

## Sentinel Best Practices:
- Use appropriate event tables for the detection
- Leverage built-in security functions
- Include time-based analysis when relevant
- Use identity and device enrichment when possible
- Apply proper filtering to reduce false positives

## Output Format:
Generate a complete Microsoft Sentinel KQL query that implements the IR logic.
Use proper KQL syntax and follow Sentinel best practices.

Now convert the following IR to a Microsoft Sentinel rule:
"""

IR_TO_QRADAR_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert an Intermediate Representation (IR) to an IBM QRadar AQL rule.

## QRadar AQL Rule Structure:
- Uses SELECT-FROM-WHERE syntax similar to SQL
- References specific log sources and event types
- Time-based filtering with STARTTIME/STIME parameters
- Aggregation functions like COUNT, SUM, AVG

## IR to QRadar AQL Mapping:
- **data_source**: Convert to appropriate log source in FROM clause
- **filter action**: Convert to WHERE clauses
- **extract action**: Convert to SELECT fields
- **group_by + aggregate**: Convert to GROUP BY with aggregation functions
- **sort action**: Convert to ORDER BY
- **limit action**: Convert to LIMIT
- **join action**: Convert to JOIN with reference data tables
- **time context**: Use STARTTIME/STIME parameters

## QRadar Best Practices:
- Use appropriate log source types for the detection
- Leverage reference data tables for enrichment
- Apply proper time filtering for correlation rules
- Use meaningful field names and aliases
- Optimize queries for performance

## Output Format:
Generate a complete QRadar AQL query that implements the IR logic.
Use proper AQL syntax and follow QRadar best practices.

Now convert the following IR to a QRadar AQL rule:
"""

IR_TO_CHRONICLE_YARAL_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert an Intermediate Representation (IR) to a Google Chronicle YARA-L rule.

## YARA-L Rule Structure:
- Event-driven detection with UDM (Unified Data Model)
- Uses specific event types and UDM fields
- Time-based correlation with "over" clause
- Built-in functions for security analysis
- Meta section for rule metadata

## IR to YARA-L Mapping:
- **data_source + event_type**: Convert to appropriate UDM event types
- **filter action**: Convert to UDM field filters
- **extract action**: Convert to UDM field references
- **group_by + aggregate**: Convert to built-in functions with grouping
- **time context**: Use "over" clause for time windows
- **join action**: Use multiple event variables for correlation

## YARA-L Best Practices:
- Use appropriate UDM event types (process, network, user, etc.)
- Leverage built-in security functions
- Apply proper time correlation for detection
- Use meaningful event variable names
- Include comprehensive meta information

## Output Format:
Generate a complete YARA-L rule with proper meta, events, and match sections.
Use proper YARA-L syntax and follow Chronicle best practices.

Now convert the following IR to a YARA-L rule:
"""

IR_TO_NETWITNESS_ESA_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to convert an Intermediate Representation (IR) to an RSA NetWitness ESA rule.

## NetWitness ESA Rule Structure:
- Uses ESA (Event Stream Analysis) rules
- Event correlation and pattern matching
- Time-based analysis with sliding windows
- Threshold-based detection
- Custom functions and expressions

## IR to NetWitness ESA Mapping:
- **data_source**: Convert to appropriate meta keys and event types
- **filter action**: Convert to meta key filters
- **extract action**: Convert to meta key references
- **group_by + aggregate**: Convert to threshold conditions
- **time context**: Use time windows for correlation
- **join action**: Use correlation rules for multiple events

## NetWitness ESA Best Practices:
- Use appropriate meta keys for the detection
- Leverage correlation rules for complex patterns
- Apply proper time windows for analysis
- Use meaningful threshold values
- Include comprehensive rule metadata

## Output Format:
Generate a complete NetWitness ESA rule that implements the IR logic.
Use proper ESA syntax and follow NetWitness best practices.

Now convert the following IR to a NetWitness ESA rule:
"""

DESCRIPTION_ANALYSE_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to analyze the following {rule_type} rule description and generate the requirements for the rule.
Below is the instruction for the task:
- You need to break down the rule description and identify the key components.
"""

RULE_CLASSIFICATION_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to classify the following splunk rule into the appropriate category.
Below is the instruction for the task:
- You will be provided with pipes of the rule and existing categories.
- If the pipe matches any of the existing categories, you need to classify the rule into that category.
- If the pipe does not match any of the existing categories, you need to create a new category for the rule.
- Your classification should be based on the functionality of the pipe.
- The output classification needs to correspond to each pipe.
- The output should be in a Markdown tabular format.

Below is an example of the output:
| Pipe                                                                                                        | Type |
|----------------------------------------------------------------------------------------------------------------|----------------------------------|
| `rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\]"` | `FIELD_EXTRACT`              |
| `eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false")` | `EVAL`                          |
| `search message!=false`                                                                                         | `FILTER`                        |
| `rename host as dest`                                                                                           | `RENAME`                        |
| `stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action`                     | `STATS`                         |
| `sort -_time`                                                                                                   | `SORT`                          |
| `crushftp_server_side_template_injection_filter`                                                                | `FILTER`                        |


"""

EXTRACT_MARKDOWN_TABLE_PROMPT = """
You are good at extracting information from text and converting it into a structured format.
Your task is to extract the following markdown table from the text and convert it into a JSON format.

Your output should be in JSON format:

Below is an example of the input and output fields:
The following is a markdown table:
| Pipe                                                                                                        | Type |
|----------------------------------------------------------------------------------------------------------------|----------------------------------|
| `eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false")` | `EVAL`                          |
| `search message!=false`                                                                                         | `FILTER`                        |
| `rename host as dest`                                                                                           | `RENAME`                        |
| `stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action`                     | `STATS`                         |
| `sort -_time`                                                                                                   | `SORT`                          |
| `crushftp_server_side_template_injection_filter`                                                                | `FILTER`                        |
The following is the extracted information:
{{
    'pipe': ['eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false")','search message!=false','rename host as dest','stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action','sort -_time','crushftp_server_side_template_injection_filter'],
    'type': ['EVAL', 'FILTER', 'RENAME', 'STATS', 'SORT', 'FILTER']
}}
"""

RULE_CLASSIFICATION_PROMPT_2 = """
You are an expert in Splunk rules and DSL design. 
Analyze the following Splunk rule and classify each pipe (separated by `|`) into one of the following DSL keywords:

{keyword}

For each pipe, output the classified keyword.
If a pipe does not match any of the keywords, output a new keyword that best describes the pipe.
Note that it is not necessary to add new ones every time. More is not always better!
Your output should be in JSON format.
For example:
{{"type": ["TYPE1", "TYPE2", "TYPE3", "TYPE4", "TYPE5", "TYPE6", ...]}}
"""

DSL_GENERATION_PROMPT = """
You are an expert in Splunk rules and DSL writing.
Your task is to generate a DSL rule based on the {rule_type} rule description and the analysis of the description.
Below is the instruction for the task:
- You will be provided with the rule description and one part of the analysis, which describes the requirements for the rule.
- You may need to generate SEVERAL DSL rules to achieve the desired functionality.
- You only need to generate the DSL rule for the given information.
- Note that the DSL rules you generate will be combined to form the final rule, so do not be duplicative.

## Below is the structure of the DSL rule:
<KEYWORD> | PARAMS {{ key1 = value1, key2 = value2, ... }} | MODULES {{ keyA = valueA, ... }}

## Below is the description of each part of the DSL rule:
- KEYWORD: describes the function of pipe (main classification).
- PARAMS: defines the required parameters of the command, such as source data, regular expression, filter conditions, etc.
- MODULES: describes optional parameters and extended functions, such as grouping, sorting, aggregate functions, subqueries, etc.

## Below is the description of the KEYWORD:
{keyword}

## Below is the description of the rule:
{rule_description}

## Below is the structure of your output:
```plaintext
<YOUR_GENERATED_DSL_RULE_1>
<YOUR_GENERATED_DSL_RULE_2>
...
```
"""

_BACKGROUND_PROMPT = """
You are a data scientist working for a cybersecurity company.
Your task is to analyze the given {rule_type} rule description and generate key insights from it.

## Below is the instruction for the task:
- You will be provided with a rule description.
- You will be asked several questions to break down the rule description and generate key logic.
- You need to select the most appropriate question to answer based on the rule description.
- If not necessary, you do not need to generate the analysis output.

## Below is the description of the rule:
{description}

## Below are the functions of the questions:
- Understanding the problem: Understand the monitoring objectives and outputs mentioned in the description.
- Identifying data sources: Identify the data sources mentioned in the description.
- Defining initial filters: Define the filtering conditions that need to be applied.
- Extracting relevant fields: Extract the fields that need to be extracted from the logs.
- Performing data aggregation: Calculate the metrics that need to be calculated.
- Calculating derived metrics: Compute any additional metrics that need to be computed.
- Filtering anomalies: Define how anomalies are identified and filtered.
"""
_UNDERSTANDING_PROBLEM_PROMPT = """
What are the monitoring objectives and outputs mentioned in the description? What fields and values need to be filtered?
"""
_IDENTIFY_DATA_SOURCE_PROMPT = """
What data sources are mentioned in the description? Are the index or sourcetype explicitly stated?
"""
_DEFINE_INITIAL_FILTERS_PROMPT = """
What filtering conditions need to be applied? Are there any values or logs that should be excluded?
"""
_EXTRACT_RELEVANT_FIELDS_PROMPT = """
Which fields need to be extracted from the logs? Do any new helper fields need to be created?
"""
_PERFORM_DATA_AGGREGATION_PROMPT = """
What metrics need to be calculated? Which fields should the data be grouped by?
"""
_CALCULATE_DERIVED_METRICS_PROMPT = """
Are there any additional metrics (e.g., success rate or anomaly score) that need to be computed? What is the calculation logic?
"""
_FILTER_ANOMALIES_PROMPT = """
How are anomalies defined? What filtering conditions or thresholds need to be applied?
"""
_OPTIMIZE_OUTPUT_PROMPT = """
What fields should be included in the final output? Do any fields need to be renamed or macros applied?
"""
TASK_BREAKDOWN_PROMPTS = {
    "BACKGROUND": _BACKGROUND_PROMPT,
    "UNDERSTANDING_PROBLEM": _UNDERSTANDING_PROBLEM_PROMPT,
    "IDENTIFY_DATA_SOURCE": _IDENTIFY_DATA_SOURCE_PROMPT,
    "DEFINE_INITIAL_FILTERS": _DEFINE_INITIAL_FILTERS_PROMPT,
    "EXTRACT_RELEVANT_FIELDS": _EXTRACT_RELEVANT_FIELDS_PROMPT,
    "PERFORM_DATA_AGGREGATION": _PERFORM_DATA_AGGREGATION_PROMPT,
    "CALCULATE_DERIVED_METRICS": _CALCULATE_DERIVED_METRICS_PROMPT,
    "FILTER_ANOMALIES": _FILTER_ANOMALIES_PROMPT,
    "OPTIMIZE_OUTPUT": _OPTIMIZE_OUTPUT_PROMPT,
}

RULE_GENERATE_PROMPT_SIMPLE = """
You are a security analyst working for a cybersecurity company.
Your task is to generate a {rule_type} rule based on the rule description, required fields and analysis of the description.

## Below is the instruction for the task:
- You need to generate the rule based on the information provided.
- You only need to generate the rule for the given information.

## Below is the structure of your output:
```spl
<YOUR_OPTIMIZED_DSL_RULE>
```
"""

DSL_OPTIMIZE_PROMPT = """
You are an expert in Splunk rules and DSL design.
Your task is to optimize the following DSL rule by removing unnecessary parts and optimizing the structure.
## Below is the instruction for the task:
- You can REMOVE, MODIFY, MERGE, or ADD parts to the DSL rule to make it more concise and efficient.
- The optimized rule should have clear logic and contain only the essential parts required to achieve the desired functionality.
- Similar functionalities can be combined or simplified.

## Below is the structure of the DSL rule:
<KEYWORD> | PARAMS {{ key1 = value1, key2 = value2, ... }} | MODULES {{ keyA = valueA, ... }}

## Below is the description of each part of the DSL rule:
- KEYWORD: describes the function of pipe (main classification).
- PARAMS: defines the required parameters of the command, such as source data, regular expression, filter conditions, etc.
- MODULES: describes optional parameters and extended functions, such as grouping, sorting, aggregate functions, subqueries, etc.

## Below is the description of the KEYWORD:
{keyword}

## Below is the structure of your output:
```plaintext
<YOUR_OPTIMIZED_DSL_RULE>
```

## Below is an example of excellent optimized DSL rule:

### Description:
This analytic is designed to identify attempts to exploit a server-side template injection vulnerability in CrushFTP, designated as CVE-2024-4040. This severe vulnerability enables unauthenticated remote attackers to access and read files beyond the VFS Sandbox, circumvent authentication protocols, and execute arbitrary commands on the affected server. The issue impacts all versions of CrushFTP up to 10.7.1 and 11.1.0 on all supported platforms. It is highly recommended to apply patches immediately to prevent unauthorized access to the system and avoid potential data compromises. The search specifically looks for patterns in the raw log data that match the exploitation attempts, including READ or WRITE actions, and extracts relevant information such as the protocol, session ID, user, IP address, HTTP method, and the URI queried. It then evaluates these logs to confirm traces of exploitation based on the presence of specific keywords and the originating IP address, counting and sorting these events for further analysis.

### Output:
```plaintext
EXTRACT | PARAMS {{ source = "_raw", regex = "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" }}

TRANSFORM | PARAMS {{ target = "message", condition = "match(_raw, 'INCLUDE') and isnotnull(src_ip)", action = "if(condition, 'traces of exploitation by ' . src_ip, 'false')" }}

FILTER | PARAMS {{ condition = "message != 'false'" }}

RENAME | PARAMS {{ fields = {{ "host" : "dest" }} }}

AGGREGATE | PARAMS {{ action = "count", fields = "_time, dest, source, message, src_ip, http_method, uri_query, user, action" }}

SORT | PARAMS {{ fields = "_time", order = "DESC" }}
```
"""

RULE_GENERATE_FROM_DSL_PROMPT = """
You are a security analyst working for a cybersecurity company.
Your task is to generate a {rule_type} rule based on the DSL rule and the analysis of the description.

## Below is the instruction for the task:
- You will be provided with the DSL rule.
- You only need to generate the rule for the given information.
- You will be given the introduction of the DSL rule.
- Based on the DSL rule and its introduction, you need to generate the corresponding {rule_type} rule.

## Below is the structure of the DSL rule:
<KEYWORD> | PARAMS {{ key1 = value1, key2 = value2, ... }} | MODULES {{ keyA = valueA, ... }}

## Below is the description of each part of the DSL rule:
- KEYWORD: describes the function of pipe (main classification).
- PARAMS: defines the required parameters of the command, such as source data, regular expression, filter conditions, etc.
- MODULES: describes optional parameters and extended functions, such as grouping, sorting, aggregate functions, subqueries, etc.

## Below is the description of the KEYWORD:
{keyword}

## Below is the structure of your output:
```spl
<YOUR_GENERATED_RULE>
```

## Below is an example of input and output:
### Input:
```plaintext
FILTER | PARAMS {{index="auth_logs", source="WinEventLog:Security", earliest=-30m}} | MODULES {{"Aggregate login attempts", "Detect brute force login attempts"}}
```
### Output:
```spl
index="auth_logs" source="WinEventLog:Security" earliest=-30m | stats count by src_ip | where count >10
```
"""

OPTIMIZE_RULE_PROMPT = """
You are an expert in SIEM rule optimization, specializing in Splunk SPL queries. Your task is to improve a given Splunk rule based on a provided ground truth rule.

## Input:
* Splunk Rule (to be improved): A Splunk SPL query that may have inefficiencies, missing filters, or suboptimal logic.
* Ground Truth Rule: A well-crafted reference SPL query that demonstrates best practices in detection logic.

## Task:
* Analyze the ground truth rule and identify its core detection logic, including key filtering conditions, field usage, and structure.
* Improve the given Splunk rule by incorporating the essential logic from the ground truth while retaining its original intent as much as possible.
* Change the whole rule or parts of it as needed to make it similar to the ground truth.
* Do NOT change the length or complexity of the original rule. But if the rule is too long, you can simplify it.
* Do NOT change the original structure of the rule, such as pipes, commands, or functions.
* Ensure the optimized rule remains efficient, accurate, and aligned with SIEM detection best practices.

## Output:
Provide the improved SPL query.

## Output Format:
```spl
<YOUR_IMPROVED_SPL_RULE>
```
"""


LLM_EVALUATION_PROMPTS = {
    "Logical Consistency": """
    Compare the logical structure of the following two Splunk rules. Do they follow the same detection logic? List any differences in conditions, operators, or filters.

    Respond with a score from 0 (completely inconsistent) to 1 (fully consistent) and explain any detected differences.
    
    Your output should be in JSON format:
    {{
        "score": SCORE,
        "explanation": "EXPLANATION"
    }}
    
    Below is an example of the input and output:
    Input:
    ```spl
    `crushftp` | rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" | eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false") | search message!=false | rename host as dest | stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action | sort -_time| `crushftp_server_side_template_injection_filter`
    ```
    Output:
    {{
        "score": 0.9,
        "explanation": "The first rule uses 'eval' to create a message field, while the second rule uses 'rex' to extract fields. Both rules filter out false messages, but the first rule has an additional 'rename' step."
    }}
    """,
    "Syntax Correctness": """
    Check if the following Splunk rule follows proper SPL syntax and best practices. Point out any errors or inefficient expressions and suggest improvements.

    Respond with a score from 0 (incorrect syntax) to 1 (perfect syntax) and list any improvements.
    
    Your output should be in JSON format:
    {{
        "score": SCORE,
        "explanation": "EXPLANATION"
    }}
    
    Below is an example of the input and output:
    Input:
    ```spl
    `crushftp` | rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" | eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false") | search message!=false | rename host as dest | stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action | sort -_time| `crushftp_server_side_template_injection_filter`
    ```
    Output:
    {{
        "score": 0.8,
        "explanation": "The rule has a valid syntax, but the 'eval' function could be simplified. The 'search' command could also be optimized to reduce processing time."    
    }}
    """,
    "Readability & Maintainability": """
    Evaluate the readability and maintainability of the following Splunk rule. Is the rule easy to understand and modify? Identify any unnecessary complexity.

    Rate from 0 (hard to read and maintain) to 1 (clear and maintainable), and explain your reasoning.
    
    Your output should be in JSON format:
    {{
        "score": SCORE,
        "explanation": "EXPLANATION"
    }}
    
    Below is an example of the input and output:
    Input:
    ```spl
    `crushftp` | rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" | eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false") | search message!=false | rename host as dest | stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action | sort -_time| `crushftp_server_side_template_injection_filter`
    ```
    Output:
    {{
        "score": 0.85,
        "explanation": "The rule is generally readable, but the use of 'eval' could be simplified. The 'rex' command is clear, but the regex could be commented for better understanding."    
    }}
    """,
    "Condition Coverage": """
    Does the following generated rule cover all the conditions specified in the ground truth rule? Highlight any missing or extra fields, filters, or logic.

    Rate from 0 (poor coverage) to 1 (full coverage) and explain the differences found.
    
    Your output should be in JSON format:
    {{
        "score": SCORE,
        "explanation": "EXPLANATION"
    }}
    
    Below is an example of the input and output:
    Input:
    ```spl
    `crushftp` | rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" | eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false") | search message!=false | rename host as dest | stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action | sort -_time| `crushftp_server_side_template_injection_filter`
    ```
    Output:
    {{
        
        "score": 0.9,
        "explanation": "The rule covers most conditions, but it does not include a check for the 'action' field being 'READ' or 'WROTE'. The regex is comprehensive, but the logic could be more explicit."
    }}
    """,
    "False Positive & False Negative Risk": """
    Analyze the following rule for its potential risk of false positives and false negatives. Is it too strict or too loose in detecting real threats?

    Respond with a score from 0 (high risk of false positives/negatives) to 1 (low risk) and explain your evaluation.
    
    Your output should be in JSON format:
    {{
        "score": SCORE,
        "explanation": "EXPLANATION"
    }}
    
    Below is an example of the input and output:
    Input:
    ```spl
    `crushftp` | rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" | eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false") | search message!=false | rename host as dest | stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action | sort -_time| `crushftp_server_side_template_injection_filter`
    ```
    Output:
    {{
        "score": 0.75,
        "explanation": "The rule is somewhat strict in filtering messages, which may lead to false negatives if the 'INCLUDE' keyword is not present. However, it does a good job of identifying potential exploitation attempts, which reduces the risk of false positives."
    }}
    """,
    "Execution Efficiency": """
    Evaluate how efficiently the following Splunk rule would run on large datasets. Are there any operations or filters that could slow down execution? Suggest possible optimizations.

    Provide a score from 0 (inefficient) to 1 (highly efficient), and suggest improvements if necessary.
    
    Your output should be in JSON format:
    {{
        "score": SCORE,
        "explanation": "EXPLANATION"
    }}
    
    Below is an example of the input and output:
    Input:
    ```spl
    `crushftp` | rex field=_raw "\[(?<protocol>HTTPS|HTTP):(?<session_id>[^\:]+):(?<user>[^\:]+):(?<src_ip>\d+\.\d+\.\d+\.\d+)\] (?<action>READ|WROTE): \*(?<http_method>[A-Z]+) (?<uri_query>[^\s]+) HTTP/[^\*]+\*" | eval message=if(match(_raw, "INCLUDE") and isnotnull(src_ip), "traces of exploitation by " . src_ip, "false") | search message!=false | rename host as dest | stats count by _time, dest, source, message, src_ip, http_method, uri_query, user, action | sort -_time| `crushftp_server_side_template_injection_filter`
    ```
    Output:
    {{
        "score": 0.8,
        "explanation": "The rule uses 'stats' and 'sort', which can be resource-intensive on large datasets. Consider using 'dedup' before 'stats' to reduce the number of events processed. The regex in 'rex' is also complex and could be optimized for performance."
    }}
    """,
}

SCORE_PROMPT = """
You are a rule reflection and optimization assistant.
You need to evaluate the following Splunk rule based on the given criteria and its ideal description.
Here is the rule to evaluate:
{rule}

Below is the description of the ideal rule:
{ideal_rule}

Rate it on:
1) Logical Coherence (0-1)
2) Syntax Validation (0-1)
3) Execution Feasibility (0-1)

Provide a JSON with your ratings and a short comment:
{{ 
  "logical_coherence": 0.0, 
  "syntax_validation": 0.0, 
  "execution_feasibility": 0.0,
  "comment": "Your analysis" 
}}
"""

RULE_OPTIMIZE_PROMPT = """
You are a Splunk rule optimization expert.
Your task is to optimize the following Splunk rule to improve its efficiency and accuracy.
You will be provided with a Splunk rule and its ideal description.
Based on the given information, optimize the rule to align with the ideal description.
The optimized rule should be as short and efficient as possible while maintaining the original logic.
Delete all unnecessary parts and simplify the rule structure.

## Below is the structure of your output:
```spl
<YOUR_GENERATED_RULE>
```
"""

a = """
index=wineventlog EventCode=4728
| eval target_user=mvindex(TargetUserName,0)
| where mvcount(TargetUserName) == 1 AND user=target_user
| stats count by user, TargetUserName


"""
